# Generated by Django 5.1.7 on 2025-03-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('desenvolvedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.desenvolvedora')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameApp.jogo')),
            ],
        ),
    ]
