# Generated by Django 5.1.7 on 2025-03-31 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
