# Generated by Django 5.1.7 on 2025-04-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(default='Descrição pendente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogo',
            name='ano_lancamento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
