# Generated by Django 5.1.7 on 2025-04-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_jogo_descricao_alter_jogo_ano_lancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nota',
            field=models.IntegerField(),
        ),
    ]
