# Generated by Django 5.1.7 on 2025-04-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0006_mensagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='enviada_em',
            new_name='data_envio',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
